Repository aditicsalunkhe/Simplii-Group74-2023, pull requests merged in 2023-11, with the labels that each got.

#2 Added frontend buttons for different features
  src/application.py
  src/templates/layout.html
Labels: enhancement

#4 Built sample analytics - Histogram
  src/.envtemplate
  src/application.py
  src/templates/analytics.html
  src/templates/layout.html
Labels: enhancement

#7 Modified Task functionality and Dashboard
  src/application.py
  src/forms.py
  src/static/js/script.js
  src/templates/dashboard.html
  src/templates/task.html
Labels: enhancement

#9 Deleted View Task and Upgraded Task Page
  src/application.py
  src/forms.py
  src/templates/layout.html
Labels: enhancement

#11 Fixed the Category filter not working in Dashboard
  src/templates/dashboard.html
Labels: bug

#20 re-implement the navbar of website; also add a site logo
  .idea/.gitignore
  .idea/Simplii-Group74-2023.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/application.py
  src/static/images/site_logo.png
  src/static/images/site_logo1.png
  src/static/images/site_logo2.png
  src/static/images/site_logo3.png
  src/static/images/site_logo4.png
  src/static/images/site_logo5.png
  src/static/images/site_logo6.png
  src/static/js/script.js
  src/static/main.css
  src/templates/layout.html
Labels: enhancement

#22 Purv dev
  src/application.py
  src/static/js/script.js
  src/templates/dashboard.html
Labels: enhancement

#19 Friend requests not showing up - Fixed
  requirements.txt
  src/application.py
  src/static/js/script.js
  src/templates/friends.html
  src/test/test_application.py
Labels: bug

#31 Removed dummy() route and recommend.html file
  src/application.py
  src/templates/recommend.html
Labels: bug

#35 Resolve welcome user message bug and do visual optimization for top navigation bar
  .idea/Simplii-Group74-2023.iml
  .idea/workspace.xml
  src/application.py
  src/static/main.css
  src/templates/layout.html
Labels: enhancement

#37 added copyright and license statements in every source code file
  .idea/workspace.xml
  models/recommend.py
  models/stats.py
  src/application.py
  src/apps.py
  src/forms.py
  src/static/Home.css
  src/static/js/script.js
  src/static/main.css
  src/templates/about.html
  src/templates/analytics.html
  src/templates/dashboard.html
  src/templates/forgotPass.html
  src/templates/friends.html
  src/templates/layout.html
  src/templates/login.html
  src/templates/register.html
  src/templates/resetPass.html
  src/templates/task.html
  static/scripts/name-block-scripts.js
  static/scripts/task-block-scripts.js
Labels: documentation

#40 Added the Forum page for open discussions
  src/application.py
  src/static/js/script.js
  src/templates/forum.html
  src/templates/friends.html
  src/templates/layout.html
  src/test/test_application.py
Labels: enhancement

#44 Added the NoneType check to the Analytics module.
  src/Simplii_App/application.py
Labels: bug

#45 Purv dev
  src/Simplii_App/application.py
  src/Simplii_App/static/js/script.js
  src/Simplii_App/templates/analytics.html
  src/Simplii_App/templates/dashboard.html
  src/Simplii_App/templates/layout.html
Labels: bug, enhancement

#50 Some front end optimizations
  .idea/.gitignore
  .idea/Simplii-Group74-2023.iml
  .idea/misc.xml
  .idea/workspace.xml
  src/Simplii_App/static/js/script.js
  src/Simplii_App/static/main.css
  src/Simplii_App/templates/layout.html
Labels: enhancement

#48 Purv dev
  src/Simplii_App/application.py
  src/Simplii_App/templates/layout.html
  src/Simplii_App/templates/rewards.html
  src/Simplii_App/test/test_application.py
Labels: enhancement

#51 Aditi dev
  src/Simplii_App/test/test_application.py
  test/test_application.py
  test/unit_test.py
Labels: bug
